> To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.

In [2]:
# import PyTorch
import torch

In [3]:
# numpy to torch and torch to numpy
import numpy as np
a = np.random.rand(4,3)
a

array([[0.22797663, 0.13888151, 0.37307876],
       [0.05313127, 0.4521244 , 0.33514257],
       [0.29877676, 0.71116642, 0.77907786],
       [0.81820368, 0.50481393, 0.50076655]])

In [4]:
b = torch.from_numpy(a)
b

tensor([[0.2280, 0.1389, 0.3731],
        [0.0531, 0.4521, 0.3351],
        [0.2988, 0.7112, 0.7791],
        [0.8182, 0.5048, 0.5008]], dtype=torch.float64)

In [5]:
b.numpy()

array([[0.22797663, 0.13888151, 0.37307876],
       [0.05313127, 0.4521244 , 0.33514257],
       [0.29877676, 0.71116642, 0.77907786],
       [0.81820368, 0.50481393, 0.50076655]])

In [6]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.4560, 0.2778, 0.7462],
        [0.1063, 0.9042, 0.6703],
        [0.5976, 1.4223, 1.5582],
        [1.6364, 1.0096, 1.0015]], dtype=torch.float64)

In [7]:
# Numpy array matches new values from Tensor
a

array([[0.45595325, 0.27776302, 0.74615752],
       [0.10626254, 0.9042488 , 0.67028514],
       [0.59755351, 1.42233284, 1.55815572],
       [1.63640735, 1.00962785, 1.00153309]])

>The memory is shared between the Numpy array and Torch tensor, so if you change the values of b, the other, a, will change as well.